### ISSUE TITLE
Documentation Error in defining Task options - missing target

### ISSUE THREAD

**Issue by purtuga** [ericf/grunt-css-selectors#1]
First of all: great plugin... Just what I needed in order to incorporate jQuery UI into an existing site without impacting the version already there.

This drove me a little crazy during setup... your example on how to setup the Grunt Task is missing the Target... It lists file, which grunt assumes to to the target, and thus when it gets down to your plugin code, it does not find a "files" parameters.

It should look like this:

```
grunt.initConfig({
  css_selectors: {
    options: {
      mutations: [
        {prefix: '.foo'}
      ]
    },
    yourTarget: {
        files: {
           'dest/foo-prefixed.css': ['src/foo.css']
        }
    }
  }
})
```

Once I made this adjustment, it all worked.

Thanks again for sharing this plugin.

**Comment by ericf** [comment]
Could you want to fix this in the docs and open a PR? Thanks!

**Comment by purtuga** [comment]
Sure... I'll try soon.

**Comment by ericf** [comment]
Merged #2, closing…

**Comment by ericf** [comment]
This is now in `v1.2.0`.

**Comment by purtuga** [comment]
Thank you.  I totally forgot about this and to send you a pull request.  

Paul
-- sent from mobile 

```
____________________________
```

**Comment by ericf** [comment]
@purtuga no worries, @lrdiv did it :)
